/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrickSelect: typeof import('./src/components/organisms/BrickSelect.vue')['default']
    Button: typeof import('primevue/button')['default']
    CalculatorVerticalForm: typeof import('./src/components/templates/CalculatorVerticalForm.vue')['default']
    Card: typeof import('primevue/card')['default']
    CardSelect: typeof import('./src/components/molecules/CardSelect.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    LightDarkToggle: typeof import('./src/components/atoms/LightDarkToggle.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MortarForm: typeof import('./src/components/organisms/MortarForm.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    QuantityInput: typeof import('./src/components/molecules/QuantityInput.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Slider: typeof import('primevue/slider')['default']
    Step: typeof import('primevue/step')['default']
    StepItem: typeof import('primevue/stepitem')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    Stepper: typeof import('primevue/stepper')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    UnitsSelect: typeof import('./src/components/atoms/UnitsSelect.vue')['default']
    WallForm: typeof import('./src/components/organisms/WallForm.vue')['default']
    WallsCollector: typeof import('./src/components/organisms/WallsCollector.vue')['default']
  }
}
